kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index, DishTypeListView, DishListView, CookListView,
    DishDetailView, CookDetailView, DishCreateView, DishUpdateView, DishDeleteView, CookCreateView, CookUpdateView,
    DishTypeFilteredListView, CookDeleteView,
)

urlpatterns = [
    path("", index,  name="index"),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/<int:pk>/filtered/",
        DishTypeFilteredListView.as_view(),
        name="dish-type-filtered"
    ),

    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),

    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
]

app_name = "kitchen"

restaurant_kitchen_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from restaurant_kitchen_service import settings


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="dishes"
    )

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "dishes"

    def get_absolute_url(self):
        return reverse("kitchen:dish-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.name}, {self.price} ({self.dish_type.name})"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["last_name"]

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.last_name} {self.first_name} ({self.username})"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Ingredient, Dish, Cook


class CookCreationForm(UserCreationForm):

    class Meta:
        model = Cook
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "email", "years_of_experience",)


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"}),
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"}),
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search type"}),
    )

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import DishForm, CookCreationForm, DishSearchForm, CookSearchForm, DishTypeSearchForm
from kitchen.models import Cook, Dish, DishType


@login_required
def index(request):
    num_dishes = Dish.objects.count()
    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()

    context = {
        "num_dishes": num_dishes,
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types
    }

    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self) -> QuerySet:
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishTypeFilteredListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "kitchen/dish_type_filtered.html"
    context_object_name = "dish_type_filtered"
    paginate_by = 5

    def get_queryset(self):
        return Dish.objects.filter(dish_type_id=self.kwargs["pk"])


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Dish.objects.all()
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )

        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    # template_name = "kitchen/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self) -> QuerySet:
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes")
    paginate_by = 2


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookCreationForm


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    # template_name = "kitchen/dish_confirm_delete.html"
    success_url = reverse_lazy("kitchen:cook-list")

templates/kitchen/cook_confirm_delete.html
{% extends "base_material.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="row">
    <header class="header-2">
    <div class="page-header min-vh-25 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
    </div>
    </header>
  </div>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <div class="row" style="margin: 0 auto">
      <div class="col-sm-12">
        <h1>Delete Cook?</h1>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, delete" class="btn btn-danger">
          <a href="javascript:history.go(-1)" class="btn btn-outline-secondary cancel">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base_material.html" %}

{% block content %}

  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
      <div class="page-header min-vh-25 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
        <span class="mask bg-gradient-primary opacity-4"></span>
      </div>
      </header>
    </div>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <div class="col-sm-8" style="margin: 0 auto">
        <h1>
          <em>{{ cook.last_name }} {{ cook.first_name }}</em>
        </h1>
        <img class="col-sm-4 rounded-3" style="float: right" src="{{ ASSETS_ROOT }}/img/cook_1.jpg" alt="cook"/>
        <p><strong>Username:</strong> {{ cook.username }}</p>
        <p><strong>Email:</strong> {{ cook.email }}</p>
        <p><strong>Experience:</strong> {{ cook.years_of_experience }} year{{ cook.years_of_experience|pluralize }}.</p>
        <a href="{% url "kitchen:cook-update" pk=cook.id %}" class="btn btn-secondary">
          Update info
        </a>
        <a href="{% url "kitchen:cook-delete" pk=cook.id %}" class="btn btn-danger">
          Delete
        </a>
        <h3>Dishes:</h3>
          {% for dish in cook.dishes.all %}
              <a href="{{ dish.get_absolute_url }}">{{ dish.name }}</a>
              <br>
            {% empty %}
              <p>He is only novice.</p>
          {% endfor %}
      </div>
    </div>
  {% endblock %}

templates/kitchen/cook_form.html
{% extends "base_material.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
      <div class="page-header min-vh-25 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
        <span class="mask bg-gradient-primary opacity-4"></span>
      </div>
      </header>
    </div>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <div class="row">

        <div class="col-sm-8" style="margin: 0 auto">
          <div class="card my-card" style="margin: 10px 10px">
            <div class="row card-body">
              <div class="col-sm-12">
                <h3 class="card-title">{{ object|yesno:"Update,Create new" }} Cook</h3>

                  <form action="" method="post" novalidate>
                    {% csrf_token %}
                    {{ form|crispy }}

                    <input class="btn btn-primary" type="submit" value="Submit">
                    <a href="javascript:history.go(-1)" class="btn btn-secondary cancel">Cancel</a>
                  </form>

              </div>
            </div>
        </div>
      </div>
    </div>
    </div>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base_material.html" %}

{% block content %}

  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
        <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
          <span class="mask bg-gradient-primary opacity-4"></span>
          <div class="container">
            <div class="row">
              <div class="col-lg-7 text-center mx-auto">
                <h1 class="text-white pt-3 mt-n5">Our Cooks</h1>
                <p class="lead text-white mt-3">From all over the world. <br /> Invite your friend. </p>
                <a class="btn btn-light" href="{% url "kitchen:cook-create" %}">Add new</a>
              </div>
            </div>
          </div>
        </div>
      </header>
    </div>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

   {% include "includes/search_form.html" %}

    {% if cook_list %}

      {% for cook in cook_list %}
        <div class="row">
          <div class="col-sm-8" style="margin: 0 auto">
            <div class="card my-card" style="margin: 10px 10px">
              <div class="row card-body">
                  <div class="col-sm-10">
                  <h4 class="card-title">{{ cook.first_name }} {{ cook.last_name }}</h4>
                  <p class="card-text"><strong>Username: </strong>{{ cook.username }}</p>
                  <p class="card-text"><strong>Experience: </strong>{{ cook.years_of_experience }} y.</p>
                  <a href="{% url 'kitchen:cook-detail' pk=cook.id %}" class="btn btn-outline-info">Detail</a>
                </div>
                <img class="col-sm-2 rounded-3" style="object-fit: cover" src="{{ ASSETS_ROOT }}/img/cook_1.jpg" alt="cook"/>
              </div>
            </div>
          </div>
        </div>

      {% endfor %}

    {% else %}
      <p>No experienced cooks free now.</p>
    {% endif %}
  {% include "includes/pagination.html" %}
  </div>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base_material.html" %}

{% block content %}
  {% include "includes/navigation.html" %}
  <div class="row">
    <header class="header-2">
    <div class="page-header min-vh-25 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
    </div>
    </header>
  </div>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <div class="row" style="margin: 0 auto">
      <div class="col-sm-12">
        <h1>Delete dish?</h1>
        <form action="" method="post">
          {% csrf_token %}

          <input type="submit" value="Yes, delete" class="btn btn-danger">
          <a href="javascript:history.go(-1)" class="btn btn-outline-secondary cancel">Cancel</a>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base_material.html" %}

{% block content %}

  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
      <div class="page-header min-vh-25 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
        <span class="mask bg-gradient-primary opacity-4"></span>
      </div>
      </header>
    </div>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <div class="col-sm-8" style="margin: 0 auto">

            <h2>
              <em>{{ dish.name }}</em>
            </h2>

            <img class="img-fluid rounded-3 mx-auto d-block"  src="{{ ASSETS_ROOT }}/img/pasta_1.jpg" alt="pasta"><p><strong>Description:</strong> {{ dish.description }}</p>

            <p><strong>Price:</strong> {{ dish.price }}</p>
            <a href="{% url "kitchen:dish-update" pk=dish.id %}" class="btn btn-secondary">
              Update info
            </a>
            <a href="{% url "kitchen:dish-delete" pk=dish.id %}" class="btn btn-danger">
              Delete
            </a>
            <div class="row">
              <div class="col-sm-6">
                <h3>Ingredients:</h3>
                {% for ingredient in dish.ingredients.all %}

                  <p>{{ ingredient.name }}</p>
                {% empty %}
                  <p>No info provided.</p>
                {% endfor %}
              </div>
              <div class="col-sm-6">
                <h3>Cooks:</h3>
                {% for cook in dish.cooks.all %}

                  <a href="{{ cook.get_absolute_url }}">{{ cook.username }}</a>
                  <br>
                {% empty %}
                  <p>Nobody can cook this!</p>
                {% endfor %}
              </div>
            </div>
      </div>

    </div>
  {% endblock %}

templates/kitchen/dish_form.html
{% extends "base_material.html" %}
{% load crispy_forms_filters %}

{% block content %}
  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
      <div class="page-header min-vh-25 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
        <span class="mask bg-gradient-primary opacity-4"></span>
      </div>
      </header>
    </div>

    <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
      <div class="row">

        <div class="col-sm-8" style="margin: 0 auto">
          <div class="card my-card" style="margin: 10px 10px">
            <div class="row card-body">
              <div class="col-sm-12">
                <h3 class="card-title">{{ object|yesno:"Update,Create new" }} Dish</h3>
                <form action="" method="post" novalidate>
                  {% csrf_token %}
                  {{ form|crispy }}

                  <input class="btn btn-primary" type="submit" value="Submit">
                  <a href="javascript:history.go(-1)" class="btn btn-secondary cancel">Cancel</a>
                </form>
              </div>
            </div>
        </div>
      </div>
    </div>
    </div>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base_material.html" %}

{% block content %}

{% include "includes/navigation.html" %}
<div class="row">
  <header class="header-2">
  <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
    <span class="mask bg-gradient-primary opacity-4"></span>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 text-center mx-auto">
          <h1 class="text-white pt-3 mt-n5">Our Dishes</h1>
          <p class="lead text-white mt-3">Explore the world of delicious food. <br /> Offer your own recipe. </p>
          <a class="btn btn-light" href="{% url "kitchen:dish-create" %}">Create new</a>
        </div>
      </div>
    </div>
  </div>
  </header>
</div>

<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

  {% include "includes/search_form.html" %}

  {% if dish_list %}

    {% for dish in dish_list %}

      <div class="row">
        <div class="col-sm-8" style="margin: 0 auto">
          <div class="card my-card" style="margin: 10px 10px">
            <div class="row card-body">
              <div class="col-sm-8">
                <h4 class="card-title">{{ dish.name }}</h4>
                <p class="card-text"><strong>Price: </strong>{{ dish.price }}</p>
                <p class="card-text"><strong>Description: </strong>{{ dish.description }}</p>
                <a href="{% url 'kitchen:dish-detail' pk=dish.id %}" class="btn btn-outline-info">Detail</a>
              </div>
              <img class="col-sm-4 rounded-3" style="object-fit: contain" src="{{ ASSETS_ROOT }}/img/pasta_1.jpg" alt="pasta"/>
            </div>
          </div>
        </div>
      </div>

    {% endfor %}

  {% else %}
    <p>No such dish in menu.</p>
  {% endif %}
{% include "includes/pagination.html" %}
</div>
{% endblock %}

templates/kitchen/dish_type_filtered.html
{% extends "base_material.html" %}

{% block content %}

  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
      <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
        <span class="mask bg-gradient-primary opacity-4"></span>
        <div class="container">
          <div class="row">
            <div class="col-lg-7 text-center mx-auto">
              {% if dish_type_filtered %}
                <h1 class="text-white pt-3 mt-n5">{{ dish_type_filtered.0.dish_type }}</h1>
                <p class="lead text-white mt-3">Explore dishes of this type. </p>
                {% else %}
                  <p class="lead text-white mt-3">No dishes of this type yet.</p>
              {% endif %}
              <a href="javascript:history.go(-1)" class="btn btn-outline-white cancel">Back to types list</a>
            </div>
          </div>
        </div>
      </div>
      </header>
    </div>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

    {% if dish_type_filtered %}

      {% for dish in dish_type_filtered %}

        <div class="row">
          <div class="col-sm-8" style="margin: 0 auto">
            <div class="card my-card" style="margin: 10px 10px">
              <div class="row card-body">
                <div class="col-sm-8">
                  <h4 class="card-title">{{ dish.name }}</h4>
                  <p class="card-text"><strong>Price: </strong>{{ dish.price }}</p>
                  <p class="card-text"><strong>Description: </strong>{{ dish.description }}</p>
                  <a href="{% url 'kitchen:dish-detail' pk=dish.id %}" class="btn btn-outline-info">Detail</a>
                </div>
                <img class="col-sm-4 rounded-3" style="object-fit: contain" src="{{ ASSETS_ROOT }}/img/pasta_1.jpg" alt="pasta"/>
              </div>
            </div>
          </div>
        </div>

      {% endfor %}

    {% endif %}

  {% endblock %}
</div>

templates/kitchen/dish_type_list.html
{% extends "base_material.html" %}

{% block content %}

  {% include "includes/navigation.html" %}
    <div class="row">
      <header class="header-2">
      <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
        <span class="mask bg-gradient-primary opacity-4"></span>
        <div class="container">
          <div class="row">
            <div class="col-lg-7 text-center mx-auto">
              <h1 class="text-white pt-3 mt-n5">Types of Dishes</h1>
              <p class="lead text-white mt-3">Explore the world of delicious food. <br /> Chose wich type you want to taste. </p>
            </div>
          </div>
        </div>
      </div>
      </header>
    </div>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

    {% include "includes/search_form.html" %}

    {% if dish_type_list %}

      {% for dish_type in dish_type_list %}

        <div class="row">

          <div class="col-sm-8" style="margin: 0 auto">
            <a href="{% url 'kitchen:dish-type-filtered' pk=dish_type.id %}">
              <div class="card my-card" style="margin: 10px 10px">
                <div class="row card-body">
                  <div class="col-sm-8">
                    <h2 class="card-title">{{ dish_type.name }}</h2>
                  </div>
                  <img class="col-sm-4 rounded-3" style="object-fit: contain" src="{{ ASSETS_ROOT }}/img/pasta_1.jpg" alt="pasta"/>
                </div>
              </div>
            </a>
          </div>
        </div>

      {% endfor %}
    {% else %}
      <p>No such dish type yet.</p>
    {% endif %}
  {% include "includes/pagination.html" %}
  </div>
  {% endblock %}

templates/kitchen/index.html
{% extends "base_material.html" %}

{#{% block content %}#}
{#	<h1>Restaurant menu</h1>#}
{#  <p>Glad to see you here!</p>#}
{#  <h3>We offer only delicious and healthy food:</h3>#}
{#  <ul>#}
{#    <li>Number of different dishes: {{ num_dishes }}</li>#}
{#    <li>Number of our cooks: {{ num_cooks }}</li>#}
{#    <li>Types of dishes: {{ num_dish_types }}</li>#}
{#  </ul>#}
{#{% endblock %}#}

{% block body_class %}

  {% include 'includes/navigation.html' %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Kitchen Service</h1>
            <p class="lead text-white mt-3">
              We offer a system for managing restaurant network kitchens.
              <br> Convenient way to monitor kitchen stuff and menu.
              <br> Join us.
            </p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_dishes }}">0</span>+</h1>
                  <h5 class="mt-3">Dishes</h5>
                  <p class="text-sm font-weight-normal">
                     A number of delicious food from our restaraunts. Meant to be cooked
                  </p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2" countto="{{ num_cooks }}">0</span>+</h1>
                  <h5 class="mt-3">Cooks</h5>
                  <p class="text-sm font-weight-normal">
                    Experienced and enthusiastic professionals from all over the world
                  </p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary" id="state3" countTo="{{ num_dish_types }}">0</h1>
                  <h5 class="mt-3">Dish types</h5>
                  <p class="text-sm font-weight-normal">
                    You will find everything you want here and much more
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>


{% endblock %}